models/Appoint.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "appoint".
 *
 * @property int $appoint_id
 * @property int|null $dep_id
 * @property int|null $bed_id
 * @property int|null $reserv_id
 * @property int|null $period_id
 * @property string|null $appoint_date
 * @property string|null $appoint_status
 * @property string|null $d_update
 *
 * @property Period $period
 * @property Bed $bed
 * @property Department $dep
 * @property Reserv $reserv
 */
class Appoint extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'appoint';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['dep_id', 'bed_id', 'reserv_id', 'period_id'], 'integer'],
            [['appoint_date', 'd_update'], 'safe'],
            [['appoint_status'], 'string'],
            [['period_id'], 'exist', 'skipOnError' => true, 'targetClass' => Period::className(), 'targetAttribute' => ['period_id' => 'period_id']],
            [['bed_id'], 'exist', 'skipOnError' => true, 'targetClass' => Bed::className(), 'targetAttribute' => ['bed_id' => 'bed_id']],
            [['dep_id'], 'exist', 'skipOnError' => true, 'targetClass' => Department::className(), 'targetAttribute' => ['dep_id' => 'dep_id']],
            [['reserv_id'], 'exist', 'skipOnError' => true, 'targetClass' => Reserv::className(), 'targetAttribute' => ['reserv_id' => 'reserv_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'appoint_id' => 'Appoint ID',
            'dep_id' => 'แผนก',
            'bed_id' => 'เตียง',
            'reserv_id' => 'ผู้รับบริการ',
            'period_id' => 'เวลา',
            'appoint_date' => 'วันนัด',
            'appoint_status' => 'สถานะ',
            'd_update' => 'วันที่ปรับปรุงล่าสุด',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPeriod()
    {
        return $this->hasOne(Period::className(), ['period_id' => 'period_id']);
    }

    public function getPeriodName(){
        return $this->period->period_name;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBed()
    {
        return $this->hasOne(Bed::className(), ['bed_id' => 'bed_id']);
    }

    public function getBedName(){
        return $this->bed->bed_name;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDep()
    {
        return $this->hasOne(Department::className(), ['dep_id' => 'dep_id']);
    }

    public function getDepName(){
        return $this->dep->dep_name;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReserv()
    {
        return $this->hasOne(Reserv::className(), ['reserv_id' => 'reserv_id']);
    }

    public function getReservName(){
        return $this->reserv->reserv_name;
    }

    public function getReservTel(){
        return $this->reserv->reserv_tel;
    }

}

controllers/AppointController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Appoint;
use app\models\AppointSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AppointController implements the CRUD actions for Appoint model.
 */
class AppointController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Appoint models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AppointSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Appoint model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionConfirm($id)
    {
        $model = $this->findModel($id);
        $model->appoint_status = '2';
        $model->save(false);
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Appoint model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Appoint();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->appoint_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Appoint model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->appoint_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Appoint model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Appoint model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Appoint the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Appoint::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/appoint/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\date\DatePicker;

use app\models\Bed;
use app\models\Department;
use app\models\Period;
use app\models\Reserv;

$dep = ArrayHelper::map(Department::find()->all(), 'dep_id', 'dep_name');
$period = ArrayHelper::map(Period::find()->all(), 'period_id', 'period_name');
$bed = ArrayHelper::map(Bed::find()->where(['dep_id' => '1'])->all(), 'bed_id', 'bed_name');
$reserv = ArrayHelper::map(Reserv::find()->all(), 'reserv_id', 'reserv_name');

/* @var $this yii\web\View */
/* @var $model app\models\Appoint */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="appoint-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'dep_id')->dropDownList($dep) ?>

    <?= $form->field($model, 'bed_id')->dropDownList($bed) ?>

    <?= $form->field($model, 'reserv_id')->dropDownList($reserv) ?>

    <?= $form->field($model, 'period_id')->radioList($period) ?>

    <?= $form->field($model, 'appoint_date')->widget(DatePicker::ClassName(),
    [
        'name' => 'appoint_date', 
        'type' => DatePicker::TYPE_INPUT,
        // 'size' => 'lg',
        // 'options' => ['placeholder' => 'Select date ...'],
        'pluginOptions' => [
        'format' => 'yyyy-mm-dd',
        'todayHighlight' => true
        ]
    ]); ?>


    <?= $form->field($model, 'appoint_status')->radioList([ 2 => 'ยืนยัน', 1 => 'จอง', 0 => 'ยกเลิก', ], ['prompt' => '']) ?>

    <?php // $form->field($model, 'd_update')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/appoint/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AppointSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="appoint-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'appoint_id') ?>

    <?= $form->field($model, 'dep_id') ?>

    <?= $form->field($model, 'bed_id') ?>

    <?= $form->field($model, 'reserv_id') ?>

    <?= $form->field($model, 'period_id') ?>

    <?php // echo $form->field($model, 'appoint_date') ?>

    <?php // echo $form->field($model, 'appoint_status') ?>

    <?php // echo $form->field($model, 'd_update') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/appoint/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Appoint */

$this->title = 'Create Appoint';
$this->params['breadcrumbs'][] = ['label' => 'Appoints', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="appoint-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/appoint/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AppointSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Appoints';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="appoint-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Appoint', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'appoint_id',
            // 'dep_id',
            [
                'attribute'=>'dep_id',
                'label'=>'แผนก',
                'format'=>'text',//raw, html
                'content'=>function($data){
                    return $data->getDepName();
                }
            ],
            // 'bed_id',
            [
                'attribute'=>'bed_id',
                'label'=>'เตียง',
                'format'=>'text',//raw, html
                'content'=>function($data){
                    return $data->getBedName();
                }
            ],
            //'reserv_id',
            [
                'attribute'=>'reserv_id',
                'label'=>'ชื่อผู้จอง',
                'format'=>'text',//raw, html
                'content'=>function($data){
                    return Html::label($data->getReservName().'<br>'.$data->getReservTel());
                }
            ],

            // 'period_id',
            [
                'attribute'=>'period_id',
                'label'=>'เวลา',
                'format'=>'text',//raw, html
                'content'=>function($data){
                    return $data->getPeriodName();
                }
            ],
            [
                'attribute'=>'appoint_date',
                'label'=>'วันจอง',
                'content'=>function($data){
                    return $data->appoint_date;
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'header' => 'สถานะ',
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'template'=>'{status}',
                'buttons'=>[
                    'status' => function($url,$model,$key){
                      return $model->appoint_status == 2 ? Html::label('ยืนยันการจอง',['class' => 'btn btn-outline-success']):Html::a('ยืนยัน',['appoint/confirm','id'=>$model->appoint_id],['class' => 'btn btn-outline-danger']);
                    }
                ]
             ],
            // 'appoint_status',
            // 'd_update',
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'header' => 'แก้ไขการจอง',
                'template'=>'{update}',
                'buttons'=>[
                    'update' => function($url,$model,$key){
                      return $model->appoint_status == 2 ? '' : Html::a('แก้ไข',['appoint/update','id'=>$model->appoint_id],['class' => 'btn btn-outline-success']);
                    }
                ]
             ],

        ],
    ]); ?>


</div>

views/appoint/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Appoint */

$this->title = 'เปลี่ยนแปลงรายการนัด: ' . $model->appoint_id;
$this->params['breadcrumbs'][] = ['label' => 'รายการนัด', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->appoint_id, 'url' => ['view', 'id' => $model->appoint_id]];
$this->params['breadcrumbs'][] = 'แก้ไข';
?>
<div class="appoint-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/appoint/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Appoint */

$this->title = $model->appoint_id;
$this->params['breadcrumbs'][] = ['label' => 'Appoints', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="appoint-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->appoint_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->appoint_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'appoint_id',
            'dep_id',
            'bed_id',
            'reserv_id',
            'period_id',
            'appoint_date',
            'appoint_status',
            'd_update',
        ],
    ]) ?>

</div>